---
- name: Set the system hostname
  hostname:
    name: '{{ uc_short_hostname }}.{{ domain }}'
  tags: base_system

- name: Set the root password for the system
  user:
    name: root
    password: '{{ root_pass }}'
    update_password: always
    state: present
  tags: base_system

- name: Ensure the configured sudo group {{ sudo_group }} exists
  group:
    name: '{{ sudo_group }}'
    state: present
  tags: base_system

- name: Create the base users for the system
  user: 
    name: '{{ item.user_name }}'
    uid: '{{ item.uid }}'
    groups: '{{ sudo_group }}'
    append: yes
    shell: /bin/bash
    password: '{{ user_pass }}'
    update_password: always
    state: present 
  loop: '{{ user_list }}'
  tags: base_system

- name: Ensure /etc/sudoers.d directory exists
  file: 
     path: /etc/sudoers.d
     state: directory
     owner: root
     group: root
     mode: 0750
  tags: base_system

- name: Create sudoers file from template
  template: 
     src: templates/extra-sudo-users.j2
     dest: /etc/sudoers.d/extra-sudo-users
     owner: root
     group: root
     mode: 0440
  tags: base_system
