---
- name: 'Get current Satellite registration status.'
  command: subscription-manager status
  register: reg_status
  ignore_errors: yes
  changed_when: false
  tags:
    - sat_install

- name: 'Install katello consumer CA on host [If not registered].'
  yum:
    name: '{{ katello_rpm_url }}'
    state: present
  retries: 10
  when: "'Unknown' in reg_status.stdout"
  tags:
    - sat_install

- name: 'Enable Satellite Registration [If not registered]'
  redhat_subscription:
    server_hostname: '{{ satellite_host }}'
    org_id: '{{ rhn_org }}'
    activationkey: '{{ rhn_activation_key }}'
    force_register: yes
    state: present
  when: "'Unknown' in reg_status.stdout"
  retries: 10
  register: sat_registration
  tags:
    - sat_install

- name: 'Disable all repositories not required.'
  rhsm_repository:
    name: '*'
    state: disabled
  when: sat_registration.changed
  retries: 10 
  tags:
    - sat_install

- name: 'Enable the configured repositories from the vars file'
  rhsm_repository:
    name: '{{ item }}'
    state: enabled
  loop: '{{ rhn_rpm_repos }}'
  when: sat_registration.changed
  register: repo_enabled
  retries: 10 
  tags:
    - sat_install
