---
- name: 'Get current Satellite registration status.'
  command: subscription-manager status
  register: reg_status
  ignore_errors: yes
  changed_when: false
  tags:
    - sat_install

- name: 'Install katello consumer CA on host [If not registered].'
  yum:
    name: '{{ katello_rpm_url }}'
    state: present
  when: "'Unknown' in reg_status.stdout"
  tags:
    - sat_install

- name: 'Enable Satellite Registration [If not registered]'
  redhat_subscription:
    server_hostname: '{{ satellite_host }}'
    org_id: '{{ rhn_org }}'
    activationkey: '{{ rhn_activation_key }}'
    state: present
  when: "'Unknown' in reg_status.stdout"
  register: sat_registration
  tags:
    - sat_install

- name: 'Disable all repositories not required.'
  rhsm_repository:
    name: '*'
    state: disabled
  when: sat_registration.changed
  tags:
    - sat_install

- name: 'Enable the configured repositories from the vars file'
  rhsm_repository:
    name: '{{ item }}'
    state: enabled
  loop: '{{ rhn_rpm_repos }}'
  when: sat_registration.changed
  tags:
    - sat_install
  register: repo_enabled
  until: repo_enabled is not failed
  retries: 5  

- name: 'Install ceph-ansible rpms.'
  yum:
    name: '{{ item }}'
    state: present
  register: ceph_rpms_install
  until: ceph_rpms_install is not failed
  retries: 5  
  loop:
    - ftp://partners.redhat.com/f0533d58c4961ffb2ee6b3877025e23b/rhel-8/Tools/x86_64/os/Packages/python3-notario-0.0.16-2.el8cp.noarch.rpm
    - ftp://partners.redhat.com/f0533d58c4961ffb2ee6b3877025e23b/rhel-8/Tools/x86_64/os/Packages/ceph-ansible-4.0.5-1.el8cp.noarch.rpm
