---
- name: Remove the cloud-init rpm before applying updates
  yum:
    name: cloud-init
    state: absent
  tags:
    - system_updates

- name: Update all installed packages
  yum:
    name: '*'
    state: latest
  register: is_updated
  until: is_updated is succeeded
  retries: 10
  delay: 5
  tags:
    - system_updates

- name: Reboot after updates
  shell: > 
    sleep 5 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: is_updated is changed
  tags:
    - system_updates

- name: Wait for host to become responsive after reboot
  wait_for_connection:
    connect_timeout: 30
    sleep: 5
    delay: 60
    timeout: 300 
  when: is_updated is changed
  tags:
    - system_updates
