---
- name: 'Remove the cloud-init rpm from the OS'
  yum:
    name: cloud-init
    state: absent

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: is_updated
  retries: 10

- name: Reboot after updates
  shell: sleep 5 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: is_updated is changed

- name:  Wait for host to become responsive.
  wait_for_connection:
    sleep: 5
    delay: 5
    timeout: 300 
  when: is_updated is changed
