---
- name: 'Perform the undercloud installation'
  shell: >
    openstack undercloud install
  args:
    chdir: /home/stack
  become: yes
  become_user: stack
  when: config_gen.changed 
  tags: undercloud_install
