---
- name: Installing tripleo packages
  yum:
    name: '{{ uc_rpm_packages }}'
    state: installed
    update_cache: yes
  register: result
  until: result is succeeded
  retries: 10
  delay: 5
  tags: undercloud_config

- name: Configure the undercloud.conf from template
  template:
    src: undercloud.conf.j2
    dest: '{{ uc_home_path }}/undercloud.conf'
    owner: stack
    group: stack
    mode: 0644
  register: config_gen
  tags: undercloud_config

- name: Create templates and image directories in {{ uc_home_path }}
  file:
    path: '{{ uc_home_path }}/{{ item }}'
    owner: '{{ uc_user }}'
    group: '{{ uc_group }}'
    mode: 0755
    state: directory
  loop:
    '{{ uc_dirs }}'
  tags: undercloud_config