---
- name: 'Copy default undercloud.conf to {{ uc_home_path }}/undercloud.conf'
  copy:
    src: /usr/share/python-tripleoclient/undercloud.conf.sample
    dest: '{{ uc_home_path }}/undercloud.conf'
    remote_src: yes
  tags: 
    - undercloud_config

- name: 'Removing default container registry search on undercloud'
  lineinfile:
    path: /etc/containers/registries.conf
    regexp: '^registries.*\[*registry.access.redhat.com|quay.io|docker.io'
    line: "registries = ['registry.redhat.io']"
    state: present
  tags: 
    - undercloud_config

- name: 'Unpacking the director images into the {{ us_home_path }}/overcloud_images directory.'
  unarchive:
    remote_src: yes
    src: '{{ item }}'
    dest: '{{ uc_home_path }}/overcloud_images'
  loop:
    - /usr/share/rhosp-director-images/overcloud-full-latest-16.0.tar
    - /usr/share/rhosp-director-images/ironic-python-agent-latest-16.0.tar
  tags: 
    - fetch_overcloud_images

