---
- name: 'Configuring Undercloud on {{ uc_short_hostname }}.{{ domain }} for installation of RHOSP 13.'
  hosts: undercloud
  roles:
    - role: install-osp13-director
  vars_files:
    - vault/vars/director-vars.yaml
  vars:
    osp_templates_repo: git@github.com:hybridpollo/osp_templates.git
    osp_templates_branch: osp13_hci
