---
- name:  'Deploying virtual machine {{ ovirt_vm_name }}'
  hosts: deploy_vm
  vars: 
    vm_domain: arl.lab
    ovirt_vm_name: 'osp-dir.{{ vm_domain }}'
    virt_vm_cpu: 4
    ovirt_vm_ram: 8Gib
    ovirt_vm_ram_guaranteed: 8Gib
    ovirt_vm_disk_size: 100Gib
    ovirt_vnic_ip: 172.25.48.10
  vars_files:
    - vault/vars/ovirt-vars.yaml
  roles:
    - role: ovirt-vm
...