---
- name: '[STARTING Playbook] Creating the Undercloud VM in RHV'
  hosts: deploy_vm
  vars:
    ansible_python_interpreter: /home/arlaporte/.python_venvs/openstack_tools/bin/python3
    vm_domain: voltron.xyz
    ovirt_vm_name: 'osp-dir.{{ vm_domain }}'
    ovirt_vm_cpu: 4
    ovirt_vm_ram: 24Gib
    ovirt_vm_ram_guaranteed: 24Gib
    ovirt_vm_disk_size: 200Gib
    ovirt_vm_dns_servers: '172.25.48.254 172.25.48.3'
    ovirt_vm_dns_search: 'voltron.xyz infra.arl.lab'
    ovirt_vm_nics:
      - nic_name: eth0
        nic_on_boot: yes
        nic_boot_protocol: static
        nic_ip_address: 172.25.48.10
        nic_netmask: 255.255.254.0
        nic_gateway: 172.25.48.1
        ovirt_nic_profile: lab_ext_net
      - nic_name: eth1
        nic_on_boot: yes
        nic_boot_protocol: none
        ovirt_nic_profile: provision_net
  vars_files:
    - vault/vars/ovirt-vars.yaml
  roles:
    - role: ovirt-vm
