---
- name: 'Deploying the director virtual machine hosted in ovirt'
  import_playbook: deploy-director-vm.yaml
  tags:
    - create_vm
- name: 'Deploying the director software on deployed vm'
  import_playbook: configure-director.yaml
  tags:
    - create_vm
