---
- name: 'Copy github keys to {{ uc_home_path }}/.ssh.'
  copy:
    src: '{{ item }}'
    dest: '{{ uc_home_path }}/.ssh' 
    owner: '{{ uc_user }}'
    group: '{{ uc_user }}'
    mode: 0600
  when: enable_git_clone == True
  loop: 
    - '{{ github_ssh_priv_key }}'
    - '{{ github_ssh_pub_key }}'
  tags: 
    - fetch_git_templates

- name: 'Ensure github.com is part of the authorized hosts'
  shell: > 
     ssh-keyscan -H github.com >> /home/stack/.ssh/known_hosts
  when: enable_git_clone == True
  tags: 
    - fetch_git_templates
    
- name:  'Create the git temporary directory with the right permissions'
  file:
    path: '{{ uc_home_path }}/.ansible/tmp'
    mode: 0755
    owner: '{{ uc_user }}'
    group: '{{ uc_user }}'
    state: directory
  when: enable_git_clone == True
  tags:
    - fetch_git_templates

- name: 'Clone git repository for RHOSP 16 templates in to {{ uc_home_path }}/overcloud_deployment.'
  git:
    repo: '{{ osp_templates_repo }}'
    version: '{{ osp_templates_branch }}'
    dest: '{{ uc_home_path }}/overcloud_deployment'
    clone: yes
    accept_hostkey: yes
  become: yes
  become_user: stack
  when: enable_git_clone == True
  tags:
    - fetch_git_templates
