---
- name: 'Create the .ssh directory structure for the {{ uc_user }} user'
  file:
    path: '{{ uc_home_path }}/.ssh'
    state: directory
    owner: '{{ uc_user }}'
    group: '{{ uc_user }}'
    mode: 0744
  tags: undercloud_config
   
- name: 'Copy local ssh keys to destination: {{ uc_home_path }}'
  copy:
    src: '{{ item }}'
    dest: '{{ uc_home_path }}/.ssh' 
    owner: '{{ uc_user }}'
    group: '{{ uc_user }}'
    mode: 0600
  loop: '{{ github_ssh_keys }}'
  tags: undercloud_config

- name:  Create the git temporary directory with the right permissions
  file:
    path: '{{ uc_home_path }}/.ansible/tmp'
    mode: 0755
    owner: '{{ uc_user }}'
    group: '{{ uc_user }}'
    state: directory
  tags: undercloud_config

- name: Ensure github.com is part of the authorized hosts
  shell: > 
     ssh-keyscan -H github.com >> /home/stack/.ssh/known_hosts
  tags: undercloud_config
    
- name: 'Clone the git repository containtaing the OSP16 templates in to /home/stack'
  git:
    repo: '{{ osp_templates_repo }}'
    version: '{{ osp_templates_branch }}'
    dest: /home/stack/osp16_templates
    clone: yes
  become: yes
  become_user: stack
  tags: undercloud_config

- name: 'Copy the undercloud.conf from the fetched git repository'
  copy:
    remote_src: yes
    src: '{{ uc_home_path }}/osp16_templates/undercloud.conf'
    dest: '{{ uc_home_path }}/undercloud.conf'
    owner: '{{ uc_user }}'
    group: '{{ uc_group }}'
  tags: undercloud_config

