---
# default  vars file for install-osp16-director
domain: arl.lab

sudo_group: wheel

time_servers:
   - clock.nyc.he.net
   - clock.fmt.he.net

user_list:
  - { user_name: stack, uid: 1001, groups: '{{ sudo_group }}' } 

uc_short_hostname: osp16-dir
uc_user: stack
uc_group: stack
uc_home_path: /home/stack
uc_dirs:
  - overcloud_images

uc_rpm_packages:
  - python3-tripleoclient
  - rhosp-director-images
  - rhosp-director-images-ipa
  - git
  - bind-utils
  - vim-enhanced
  - tmux

# rhn activation name and key are vaulted
# vault/vars/director-vars.yaml
satellite_host: satellite.infra.arl.lab
katello_rpm_url: 'http://{{ satellite_host }}/pub/katello-ca-consumer-latest.noarch.rpm'

rhn_rpm_repos:
  - rhel-8-for-x86_64-baseos-rpms 
  - rhel-8-for-x86_64-appstream-rpms 
  - rhel-8-for-x86_64-highavailability-rpms 
  - ansible-2.8-for-rhel-8-x86_64-rpms 
  - openstack-16-for-rhel-8-x86_64-rpms
  - satellite-tools-6.5-for-rhel-8-x86_64-rpms
  - fast-datapath-for-rhel-8-x86_64-rpms

# List of ssh keys are used to bootstrap git when enabled
enable_git_clone: false
github_ssh_priv_key: /home/arlaporte/.ssh/id_rsa
github_ssh_pub_key: /home/arlaporte/.ssh/id_rsa.pub

# Git repository to clone
osp_templates_repo: git@github.com:hybridpollo/osp_templates.git
osp_templates_branch: osp16_home_lab

# variables used for nova join
# and tls everywhere
enable_tls_everywhere: false
idm_domain: voltron.xyz
idm_server: 'idm.{{ idm_domain }}'
tls_everywhere_rpm_deps:
  - python3-nss
  - python3-novajoin

# undercloud.conf parameters
# these variables below are used to configure the undercloud.conf
# not every variable is parametrized
# please review the default file 
# /usr/share/instack-undercloud/undercloud.conf.sample 
# for all available parameters
# overcloud domain if different from {{ domain}}
overcloud_domain: arl.lab
undercloud_local_interface: eth1
undercloud_local_mtu: 1500
undercloud_enable_uefi: false
undercloud_enable_debug: false
undercloud_enable_telemetry: False
undercloud_enable_tempest: false
undercloud_enable_ui: false
undercloud_enable_clean_nodes: true
undercloud_enable_clean_up: true
undercloud_enable_selinux: true
undercloud_enable_ipxe: True
undercloud_enable_inspection_extras: True
undercloud_container_cli: podman
undercloud_container_images_file: '{{ uc_home_path }}/container_image_prepare.yaml'
undercloud_custom_environment_file: '{{ uc_home_path }}/undercloud_custom_env.yaml'
undercloud_inspection_interface: br-ctlplane
undercloud_local_subnet: ctlplane-subnet
undercloud_local_ip: 172.16.24.2/24
undercloud_public_vip: 172.16.24.3
undercloud_admin_vip: 172.16.24.4
undercloud_provisioning_cidr: 172.16.24.0/24
undercloud_dhcp_provisioning_start: 172.16.24.5
undercloud_dhcp_provisioning_end: 172.16.24.24
undercloud_dhcp_inspection_start: 172.16.24.100
undercloud_dhcp_inspection_end: 172.16.24.120
undercloud_dhcp_gateway: 172.16.24.1
undercloud_enable_masquerade: False
undercloud_name_servers:
  - 172.25.48.3
  - 8.8.8.8
undercloud_time_servers:
   - clock.nyc.he.net
   - clock.fmt.he.net
undercloud_enable_routed_networks: False
undercloud_routed_subnets_list:
  - ctlplane-subnet
undercloud_enabled_hardware_types:
  - staging-ovirt
  - ilo
  - ipmi
undercloud_container_registry_address: 172.16.24.2:8787
container_registry_username: '5318211|rhn-gps-ariveral'
container_registry_password: 'eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiIwMGY0MWEzODc3YTc0NzEyYjY1ODcxNTg5MGQ4Yjc4YSJ9.vQHC_hsKDxGTiZ8ilJyCBsmYUr1nCpznXHI_hvNiqBA2_WyMr-FXvi9GOVHN8AF0_2LCjTgJAgijSLZuRJhav7faFsnovuWvCJ7Os4-BpnoSHFzKX_kwsV8suPzl9FxQnezpgbE6gMUp2PVg0wpYvB9r9cC3vnF16vRXbqjM9vF-U-h26vAhWYONthgO8WWaOTILCJtGAe1kUZk9STxspFTIhmmw8G3xIhgnCEBEcQPAAYQpW4jNBj0JtoFHBVukxs6CFiczZ_z_EL2E88zD6M_Xo4n-DTrmmVI4lxbjCo_Z2lxz0ws9Y81hnMagsXHP6Waod1tvVIWIvh9p8iWBuz8Z4EDO1M5g-RIWkj3RhNypgufUM9coBTgSJVpTljh3IvaQlV_AaZAmm6ObBkTzBZGRyik38nqbA5WUkjzN8TlIphjecpp2D-RVOtF7pzXSNVPjEPGY_BKaz-_UrZdNvO7stQw0jq7C5h5OpyIIrLNqh-j-QW7glNcF14o6ItizoH5pF74gaXHB_QWUfXcGa_zQTtuvjlIl4vpvKuHI1igw-p4VRJMfdQgmHeDB0UlPgLmsMeAnml3nQZNx1vqOoMwqfthOv5Ty6LfQm4I7M5-59V2j4DkNQp4gqIcmLKdW5LLFK-RwBb2aHuqkXlh4CJ-cOWZyLjB_sBa6OldVfQ4'