---
# default  vars file for install-director
domain: voltron.xyz

sudo_group: wheel

time_servers:
   - clock.nyc.he.net
   - clock.fmt.he.net
   - clock.sjc.he.net

user_list:
  - { user_name: stack, uid: 1001, groups: '{{ sudo_group }}' } 

uc_short_hostname: osp-dir
uc_user: stack
uc_group: stack
uc_home_path: /home/stack
uc_dirs:
  - overcloud_images
  - templates

uc_rpm_packages:
  - python-tripleoclient
  - rhosp-director-images
  - rhosp-director-images-ipa
  - git
  - bind-utils
  - ceph-ansible

# rhn activation name and key are vaulted
# vault/vars/director-vars.yaml
satellite_host: satellite.infra.arl.lab
katello_rpm_url: 'http://{{ satellite_host }}/pub/katello-ca-consumer-latest.noarch.rpm'

rhn_rpm_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-satellite-tools-6.3-rpms
  - rhel-ha-for-rhel-7-server-rpms
  - rhel-7-server-openstack-13-rpms
  - rhel-7-server-rhceph-3-tools-rpms

# List of ssh keys are used to bootstrap git
# these are copied via the inject-ssh-key.yaml task
github_ssh_keys:
  - /home/arlaporte/.ssh/id_rsa
  - /home/arlaporte/.ssh/id_rsa.pub
