---
# default  vars file for install-director
domain: voltron.xyz

sudo_group: wheel

time_servers:
   - 0.pool.ntp.org
   - 1.pool.ntp.org
   - 2.pool.ntp.org

user_list:
  - { user_name: stack, uid: 1001, groups: '{{ sudo_group }}' } 

uc_short_name: osp13-dir
uc_user: stack
uc_group: stack
uc_home_path: /home/stack
uc_dirs:
  - images
  - templates

uc_packages:
  - python-tripleoclient
  - rhosp-director-images
  - rhosp-director-images-ipa

# rhn activation name and key are vaulted
# vault/vars/director-vars.yaml
satellite_host: satellite.infra.arl.lab

rhn_rpm_repos:
  - rhel-7-server-rpms 
  - rhel-7-server-extras-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-satellite-tools-6.3-rpms
  - rhel-ha-for-rhel-7-server-rpms
  - rhel-7-server-openstack-13-rpms

