---
- name: 'Obtain SSO token using username/password credentials'
  ovirt_auth:
    url: '{{ ovirt_url }}'
    username: '{{ ovirt_username }}'
    password: '{{ ovirt_password }}'
    state: present
  register: result
  tags:
    - create_vm
    - delete_vm 

- name: 'Creating virtual machine: {{ ovirt_vm_name }}.'
  ovirt_vm:
    auth: '{{ ovirt_auth }}'
    name: '{{ ovirt_vm_name }}'
    cluster: '{{ ovirt_cluster_name }}'
    template: '{{ ovirt_vm_template }}'
    memory: '{{ ovirt_vm_ram }}'
    memory_guaranteed: '{{ ovirt_vm_ram_guaranteed }}'
    cloud_init_persist: true 
    cpu_sockets: '{{ ovirt_vm_cpu }}'
    cloud_init:
      host_name: '{{ ovirt_vm_name }}'
      user_name: '{{ ovirt_vm_username }}'
      root_password: '{{ ovirt_vm_root_passwd }}'
      authorized_ssh_keys: '{{ ovirt_vm_ssh_key }}'
      dns_servers: '{{ ovirt_vm_dns_servers }}'
      dns_search: '{{ ovirt_vm_dns_search }}'
    cloud_init_nics: '{{ ovirt_vm_nics }}'
    state: present
  when: ovirt_vm_state == "running" or ovirt_vm_state == "present"
  tags: 
    - create_vm

- name: 'Deleting virtual machine: {{ ovirt_vm_name }}'
  ovirt_vm:
    auth: '{{ ovirt_auth }}'
    name: '{{ ovirt_vm_name }}'
    cluster: '{{ ovirt_cluster_name }}'
    template: '{{ ovirt_vm_template }}'
    state: 'absent'
  when: ovirt_vm_state == "present" and "delete_vm" in ansible_run_tags 
  tags: 
    - delete_vm

- name: 'Retrieving facts for disk sizing and nic allocation'
  ovirt_vm_info:
    auth: '{{ ovirt_auth }}'
    pattern: 'name={{ ovirt_vm_name }}'
    fetch_nested: true
    all_content: true
  register: vm_info
  tags:
    - create_vm

- name: "Change disk size of {{ ovirt_vm_name }} to desired size {{ ovirt_vm_disk_size }}"
  ovirt_disk:
    auth: '{{ ovirt_auth }}'
    vm_name: '{{ ovirt_vm_name }}'
    size: '{{ ovirt_vm_disk_size }}'
    id: '{{ vm_info.ovirt_vms[0].disk_attachments[0].id }}'
    state: attached
  when: vm_info.ovirt_vms[0].disk_attachments[0].id is defined and vm_info.ovirt_vms[0].status is defined
  tags:
    - create_vm

- name: "Attaching vnic profile to virtual machine."
  ovirt_nic:
    auth: '{{ ovirt_auth }}'
    vm: '{{ ovirt_vm_name }}'
    name: '{{ item.nic_name }}'
    profile: '{{ item.ovirt_nic_profile }}'
    network: '{{ item.ovirt_nic_profile }}'
    state: present
  loop: '{{ ovirt_vm_nics }}'
  when: vm_info.ovirt_vms[0].status is defined
  tags:
    - create_vm

- name: Pause for 10 seconds before booting machine 
  pause:
    seconds: 10
  tags:
    - create_vm

- name: 'Starting virtual machine: {{ ovirt_vm_name }}'
  ovirt_vm:
    auth: '{{ ovirt_auth }}'
    name: '{{ ovirt_vm_name }}'
    state: running
  when: vm_info.ovirt_vms[0].status is defined and vm_info.ovirt_vms[0].status == 'down'
  tags:
    - create_vm

- name: Revoking SSO Token....
  ovirt_auth:
    state: absent
    ovirt_auth: '{{ ovirt_auth }}'
  tags:
    - create_vm
    - delete_vm 