---
# default parameters
# The variables are defined in the vault file
#ovirt_url
#ovirt_cluster_name
#ovirt_username
#ovirt_password:
#rhn_activation_key
#ovirt_vm_root_passwd:
#ovirt_vm_ssh_key:
# end variables defined in vault file

# General Settings
domain: infra.arl.lab

# Virtual Machine Settings
ovirt_vm_state: present
ovirt_vm_name: 'test.{{domain}}'
ovirt_vm_cpu: 2
ovirt_vm_ram: 8Gib
ovirt_vm_ram_guaranteed: 8Gib
ovirt_vm_disk_size: 60Gib
ovirt_vm_username: root
ovirt_vm_template: rhel-7-8-template
ovirt_vm_dns_servers: "172.25.48.3 8.8.4.4"
ovirt_vm_dns_search: '{{ domain }}'

# dictionary of vm nics to be configured example
# additional information
# https://docs.ansible.com/ansible/latest/modules/ovirt_vm_module.html#parameter-cloud_init_nics
#ovirt_vm_nics:
#  - nic_name: eth0
#    nic_on_boot: yes
#    nic_boot_protocol: static
#    nic_ip_address: 172.25.100.10
#    nic_netmask: 255.255.255.0
#    nic_gateway: 172.25.100.1
#    ovirt_nic_profile: home_wired_net
#  - nic_name: eth1
#    nic_on_boot: yes
#    nic_boot_protocol: static
#    nic_ip_address: 172.25.54.10
#    nic_netmask: 255.255.255.0
#    ovirt_nic_profile: storage_mgmt
